# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getMatrixZj0 <- function(Z, k1, k_tot, j) {
    .Call(`_odpc_getMatrixZj0`, Z, k1, k_tot, j)
}

getMatrixFore <- function(f, k2, h) {
    .Call(`_odpc_getMatrixFore`, f, k2, h)
}

getMatrixFitted <- function(f, k1, k2) {
    .Call(`_odpc_getMatrixFitted`, f, k1, k2)
}

getFini_forecast <- function(Z, resp, k1, k2, num_comp) {
    .Call(`_odpc_getFini_forecast`, Z, resp, k1, k2, num_comp)
}

getMatrixF_sparse_forecast <- function(Z, k1, k2, k_tot, a) {
    .Call(`_odpc_getMatrixF_sparse_forecast`, Z, k1, k2, k_tot, a)
}

getMSE <- function(resp, Fitted) {
    .Call(`_odpc_getMSE`, resp, Fitted)
}

odpc_priv <- function(Z, resp, k_tot_max, k1, k2, num_comp, f_ini, passf_ini, tol, niter_max, method) {
    .Call(`_odpc_odpc_priv`, Z, resp, k_tot_max, k1, k2, num_comp, f_ini, passf_ini, tol, niter_max, method)
}

roll_odpc <- function(data_field, response_field, k, k_tot_max, num_comp, window_size, tol, niter_max, method, ncores) {
    .Call(`_odpc_roll_odpc`, data_field, response_field, k, k_tot_max, num_comp, window_size, tol, niter_max, method, ncores)
}

